apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd
          ports:
            - containerPort: 24224
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
              subPath: fluent.conf
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
