replicaCount: 3
service:
  type: LoadBalancer
  port: 9090

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  environment: production

alertmanager:
  enabled: true
  config:
    global:
      smtp_smarthost: 'smtp.example.com:25'
      smtp_from: 'alertmanager@example.com'
