apiVersion: v1
kind: Service
metadata:
  name: simple-monitored-app-service
  labels:
    app: simple-monitored-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: simple-monitored-app
